### ISSUE TITLE
伺服器無法連線

### ISSUE THREAD

**Issue by m42040** [ychsiao/pushisland#1]
伺服器又斷線啦

**Comment by ychsiao** [comment]
fixed XD
我來問ed是有裝了什麼

Cheers,
ychsiao
LinkedIn http://tw.linkedin.com/in/ychsiao

**Comment by ychsiao** [comment]
先拿掉slack plugin

**Comment by m42040** [comment]
又斷線了?

**Comment by edwardchuang** [comment]
據說改架構，請試試看？

**Comment by ychsiao** [comment]
sorry, 機房端有排定改路由造成四小時斷線:/
