### ISSUE TITLE
我想當個正常人

### ISSUE THREAD

**Issue by huskyl** [ychsiao/pushisland#16]
<img width="852" alt="screen shot 2016-10-08 at 9 29 03 pm" src="https://cloud.githubusercontent.com/assets/19179850/19213399/57e2250a-8d9e-11e6-8729-4ff39ce9bc3e.png">

大大可以幫我把那個 Cosmetics 拿掉嗎?

**Comment by ychsiao** [comment]
![minecraft 1 9 4 minecraft today at 9 40 48 pm](https://cloud.githubusercontent.com/assets/652160/19213490/404e8cf6-8da0-11e6-8edb-cbe304da0844.png)
fixed XD
