### ISSUE TITLE
宣傳伺服器

### ISSUE THREAD

**Issue by m42040** [ychsiao/pushisland#5]
請問我可以把伺服器貼到巴哈姆特嗎? 我想把伺服器推廣出去

**Comment by ychsiao** [comment]
可以啊，不過要把正版驗證打開
然後有人要當副島主嗎XDDD

**Comment by m42040** [comment]
那請問可以給我伺服器網路頻寬圖嗎? 我要用在巴哈招生文上

**Comment by ychsiao** [comment]
http://p.mc.pushpush.org
頻寬1G :)
