### ISSUE TITLE
動物

### ISSUE THREAD

**Issue by m42040** [ychsiao/pushisland#9]
請問可不可以放幾隻狼出來 因為狼都生不出來QAQ

**Comment by edwardchuang** [comment]
來個座標？

**Comment by m42040** [comment]
可以放一些狼蛋嗎 我覺得伺服器其他人也想養狗
X=-267 Y=63 Z=-363(箱子的)

**Comment by edwardchuang** [comment]
放了幾顆，先看看

**Comment by edwardchuang** [comment]
這張可關

**Comment by m42040** [comment]
是不是可以先裝1.7.10版的 因為礦車沒有自帶chunk londer 開太遠會自己卡住 而且有些機制要是用原版紅石蓋會很困難
再加上現在礦車只要撞到生物就會彈回 遭成車子回頭卡住其他車子 癱瘓整個系統 謝謝

edwardc notifications@github.com 於 2015年11月12日 星期四寫道：

**Comment by edwardchuang** [comment]
我有找過，似乎沒辦法
直接 1.8 真的會比較簡單

2015-11-17 18:29 GMT+08:00 m42040 notifications@github.com:

**Comment by m42040** [comment]
可是我這邊測試直接丟進去(spigot)就可以了阿

edwardc notifications@github.com 於 2015年11月17日 下午6:32 寫道：
